### ISSUE TITLE
Input 1KG BED file isn't actually in BED format

### ISSUE THREAD

**Issue by sean-la** [DCGenomics/DangerTrack#3]
I've been working on lifting over the 1000 genomes BED file to GRCh38 using NCBI's `remap` API, and it seems that the BED file for the 1000 genomes SV calls (i.e. `sv.1kg.bed`) isn't actually in BED format. According to a developer at NCBI, for each entry in the BED file, the start position should be strictly less than the stop position. However, for each entry in the `sv.1kg.bed` file, the start and stop positions are equal. If I were to increment each entry's stop position by 1 in the `sv.1kg.bed` file, would DangerTrack still work?

**Comment by igordot** [comment]
Sometimes coordinate systems are 0-based (numbers between nucleotides, so the first base in a chromosome is numbered 0) and other times they are 1-based (numbers nucleotides directly). To convert from 1-based to 0-based, subtract 1 from the start position. It should still work with DangerTrack. If not, let us know.

**Comment by sean-la** [comment]
This worked, thank you!
